# Generated by Django 5.2.13 on 2026-04-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'market_exchange',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.exchange')),
            ],
            options={
                'db_table': 'market_symbol',
                'unique_together': {('exchange', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('pk', models.CompositePrimaryKey('interval', 'symbol', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('interval', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=16)),
                ('high', models.DecimalField(decimal_places=8, max_digits=16)),
                ('low', models.DecimalField(decimal_places=8, max_digits=16)),
                ('close', models.DecimalField(decimal_places=8, max_digits=16)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=16)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.symbol')),
            ],
            options={
                'db_table': 'market_security',
            },
        ),
    ]
