# Generated by Django 5.2.13 on 2026-04-14 01:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_symbol_pk_ticker_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='symbol',
            field=models.ForeignKey(
                db_column='symbol',
                on_delete=django.db.models.deletion.CASCADE,
                to='market.symbol',
                to_field='symbol',
            ),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='symbols',
                to='market.exchange'),
        ),
    ]
