# Generated by Django 5.2.13 on 2026-04-14 01:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_security_fk_db_column_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
