# Generated by Django 5.2.13 on 2026-04-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_exchange_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Security',
            new_name='Bars',
        ),
        migrations.AlterModelTable(
            name='bars',
            table='market_bars',
        ),
    ]
