# Generated by Django 5.2.13 on 2026-04-14 04:43

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_bars_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='symbol',
            field=models.ForeignKey(
                db_column='symbol',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bars',
                to='market.symbol',
                to_field='symbol',
            ),
        ),
    ]
