# Generated by Django 5.2.13 on 2026-04-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_bars_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='symbol',
            field=models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='market.symbol'),
        ),
    ]
