# Generated by Django 5.2.13 on 2026-04-14 20:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_rename_market_security_table_to_market_bars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='bars',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='bars',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='bars',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='bars',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
    ]
