# Generated by Django 6.0.1 on 2026-01-23 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('trader', models.CharField(db_index=True, max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('change_type', models.CharField(choices=[('NEW', 'New Position'), ('ADD', 'Add to Position'), ('TRIM', 'Trim Position'), ('CLOSE', 'Close Position'), ('FLIP', 'Flip Position')], db_index=True, max_length=10)),
                ('net_side', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('flat', 'Flat')], max_length=10)),
                ('delta_magnitude', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'executions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'trader'], name='executions_timesta_e0ff36_idx'), models.Index(fields=['symbol', '-timestamp'], name='executions_symbol_5f7e45_idx'), models.Index(fields=['change_type', '-timestamp'], name='executions_change__c04790_idx'), models.Index(fields=['trader', 'symbol', '-timestamp'], name='executions_trader_742789_idx')],
            },
        ),
    ]
