# Generated by Django 6.0.1 on 2026-01-24 22:16

import django.utils.timezone
from django.db import migrations, models

# shell promt to make migrations file:
# python manage.py makemigrations executions
# shell primt to apply migrations:
# python manage.py migrate
class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('trader', models.CharField(db_index=True, max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('instrument_type', models.CharField(choices=[('equity', 'Equity'), ('option', 'Option')], db_index=True, max_length=10)),
                ('underlying', models.CharField(db_index=True, max_length=20)),
                ('expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('C', 'Call'), ('P', 'Put')], max_length=1, null=True)),
                ('is_long_term', models.BooleanField(db_index=True, default=False)),
                ('net_side', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('flat', 'Flat')], max_length=10)),
                ('conflict', models.BooleanField(default=False)),
                ('total_magnitude', models.FloatField(default=0.0)),
                ('prev_magnitude', models.FloatField(blank=True, null=True)),
                ('delta_magnitude', models.FloatField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, choices=[('NEW', 'New Position'), ('ADD', 'Add to Position'), ('TRIM', 'Trim Position'), ('CLOSE', 'Close Position'), ('FLIP', 'Flip Position'), ('', 'No Change')], db_index=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['trader', 'underlying', '-total_magnitude'],
                'indexes': [models.Index(fields=['-timestamp', 'trader'], name='positions_timesta_200369_idx'), models.Index(fields=['trader', 'underlying', '-total_magnitude'], name='positions_trader_0f1155_idx'), models.Index(fields=['trader', 'underlying', '-timestamp'], name='positions_trader_bb862e_idx'), models.Index(fields=['instrument_type', '-timestamp'], name='positions_instrum_62f319_idx'), models.Index(fields=['timestamp', 'trader', 'symbol'], name='positions_timesta_f04598_idx')],
                'unique_together': {('timestamp', 'trader', 'symbol')},
            },
        ),
    ]
