# Generated by Django 6.0.1 on 2026-03-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='risk_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='total_risk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
