# Generated by Django 6.0.1 on 2026-03-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_add_execution_risk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='market_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
