# Generated by Django 6.0.1 on 2026-03-19 23:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_add_execution_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='risk_percent',
            field=models.FloatField(blank=True, db_column='risk_%', null=True),
        ),
    ]
