# Generated by Django 6.0.1 on 2026-03-19 23:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_add_execution_risk_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='filled_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
